Name:           perl-AnyEvent-Log-AIO
Version:        0.01
Release:        1%{?dist}
Summary:        AnyEvent::Log::AIO Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-Log-AIO/
Source0:        http://www.cpan.org/modules/by-module/AnyEvent/AnyEvent-Log-AIO-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(AnyEvent) >= 7
BuildRequires:  perl(AnyEvent::AIO)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(IO::AIO)
BuildRequires:  perl(Mouse) >= 1.11
BuildRequires:  perl(Time::Moment)
Requires:       perl(AnyEvent) >= 7
Requires:       perl(AnyEvent::AIO)
Requires:       perl(IO::AIO)
Requires:       perl(Mouse) >= 1.11
Requires:       perl(Time::Moment)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
AnyEvent::Log::AIO Perl module

%prep
%setup -q -n AnyEvent-Log-AIO-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json MYMETA.json MYMETA.yml README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jul 06 2017 Mons Anderson <mons@cpan.org> 0.01-1
- Specfile autogenerated by cpanspec 1.78.
